# Generated by Django 5.1.5 on 2025-01-27 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfileModel',
            fields=[
                ('LicenseNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Specialist', models.TextField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('Record', models.TextField()),
                ('SensitiveInformation', models.TextField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctorprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('MedicalID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Age', models.PositiveIntegerField()),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('Address', models.TextField()),
                ('Country', models.CharField(max_length=30)),
                ('QRCode', models.ImageField(null=True, upload_to='QRCode')),
                ('ProfilePic', models.ImageField(blank=True, null=True, upload_to='ProfilePic')),
                ('MedicalRecord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.medicalrecordmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
