# Generated by Django 5.1.5 on 2025-01-27 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='Age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='Country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='MedicalRecord',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medicalrecordmodel'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='PhoneNumber',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='QRCode',
            field=models.ImageField(blank=True, null=True, upload_to='QRCode'),
        ),
    ]
