# Generated by Django 5.1.5 on 2025-01-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userprofilemodel_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofilemodel',
            old_name='Specialist',
            new_name='Specialization',
        ),
        migrations.RemoveField(
            model_name='medicalrecordmodel',
            name='Record',
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='AdditionalNotes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='Diagnosis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='HospitalName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='Symptoms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='TestsConducted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='TreatmentPlan',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='Date',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='SensitiveInformation',
            field=models.TextField(null=True),
        ),
    ]
