# Generated by Django 5.1.5 on 2025-01-28 00:28

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_specialist_doctorprofilemodel_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Perfer not to say', 'Perfer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='MedicalID',
            field=models.CharField(default=app.models.generate_MedicalId, max_length=7, primary_key=True, serialize=False),
        ),
    ]
