# Generated by Django 5.1.5 on 2025-01-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofilemodel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofilemodel',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofilemodel',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='ProfilePic'),
        ),
    ]
